import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Footer } from "react-day-picker";
import Header from "@/components/Header";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
     <ClerkProvider appearance={{
     theme: dark,
   }}>
      <html lang="en" suppressHydrationWarning>
        <head />
        <body  className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Header/>
            <main className="min-h-screen">{children}</main>
            <Toaster richColors/>
            {/* footer */}
            <Footer className="bg-muted/50 py-12">
              <div className="container px-4 mx-auto text-center">
                <p>Made with ❤️ By Sudeep Sahu</p>
              </div>
            </Footer>
          </ThemeProvider>
        </body>
      </html>
      </ClerkProvider>
    </>
  )
}

